# Generated by Django 4.2 on 2023-04-20 20:06

import accounts.path_resolvers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, help_text='avatar, file resolution must be *.jpeg, *.jpg or *.png', null=True, upload_to=accounts.path_resolvers.profile_avatar_path, verbose_name="user's avatar")),
                ('phone', phone_field.models.PhoneField(blank=True, default='', help_text='phone in international format', max_length=31, verbose_name='phone')),
                ('user', models.OneToOneField(help_text='user that owns this profile', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
