# Generated by Django 4.2 on 2023-04-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_format', models.CharField(choices=[('mm/dd/yyyy', '%m/%d/%Y'), ('HH:MM mm.dd.yyyy', '%H:%M %d.%m.%Y')], help_text='choose datetime format that will be represented through entire project', verbose_name='datetime formats')),
                ('regular_delivery_cost', models.DecimalField(decimal_places=2, default=200, help_text='choose regular delivery cost that will be represented through entire project', max_digits=10, verbose_name='cost of regular delivery')),
                ('express_delivery_cost', models.DecimalField(decimal_places=2, default=700, help_text='choose express delivery cost that will be represented through entire project', max_digits=10, verbose_name='cost of express delivery')),
                ('popular_products_amt', models.PositiveSmallIntegerField(default=8, help_text='choose amount of popular products that will be represented at main page', verbose_name='amount of popular products at main page')),
                ('limited_products_amt', models.PositiveSmallIntegerField(default=16, help_text='choose amount of limited products that will be represented at main page', verbose_name='amount of limited products at main page')),
                ('banners_amt', models.PositiveSmallIntegerField(default=4, help_text='choose amount of banners that will be represented at main page', verbose_name='amount of banners at main page')),
                ('cache_time', models.PositiveIntegerField(default=7200, help_text='choose time in seconds during which data will be cached', verbose_name='cache time')),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
    ]
