# Generated by Django 4.2 on 2023-04-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytype',
            name='type',
            field=models.CharField(choices=[('обычная', 'Regular'), ('express', 'Express')], default='обычная', max_length=50, verbose_name='type'),
        ),
    ]
